### ISSUE TITLE
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf" "autoreconf"

### ISSUE THREAD

**Issue by zzroche** [imagemin/gifsicle-bin#102]
I've a problem when I try to intall gifsicle...

 ‼ tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
"autoreconf" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

**Comment by littlegrayss** [comment]
I had the same issue, how did you resolve this?

**Comment by oo10** [comment]
> 尝试安装gifsicle时出现问题...
> 
> ！无法建立隧道套接字，原因=连接ECONNREFUSED 127.0.0.1:80！gifsicle
> 预生成测试失败，
> 我从源代码编译
> ×错误：命令失败：C：\ WINDOWS \ system32 \ cmd.exe / s / c“ autoreconf -ivf“
> ” autoreconf“非riconosciuto随叫随到，不带批注，可以从
> 程序中指定。

I have the same problem. How can you solve it?
