### ISSUE TITLE
Lambda Support

### ISSUE THREAD

**Issue by KempfCreative** [imagemin/gifsicle-bin#112]
Hello! This is a great lib. I was hoping that you could make it possible to use this as a direct dependency in a NodeJS AWS Lambda? Right now, using it as per the README will result in an error on runtime:
`/var/task/lambda/node_modules/gifsicle/vendor/gifsicle: /var/task/lambda/node_modules/gifsicle/vendor/gifsicle: cannot execute binary file`

I can always pull down the binary, make and install it, and then use exodus to bundle the binary with my NodeJS app, but that kind of defeats the purpose of this NPM module :)

**Comment by nisalikularatne** [comment]
Is there any update on this issue? It seems like gipsicle currently cannot run on a lambda runtime.

**Comment by mreinstein** [comment]
I believe this is a duplicate of #104

**Comment by mreinstein** [comment]
I think this is resolved via #118

**Comment by KempfCreative** [comment]
I haven't tested it, but based on the merged commit it seems like it will be fixed. Thanks for taking care of it!

**Comment by phgnam** [comment]
It still is not working at v7.0.1
