### ISSUE TITLE
dont force esm

### ISSUE THREAD

**Issue by skeddles** [imagemin/gifsicle-bin#130]
Seems you made it start forcing esm 13 days ago: https://github.com/imagemin/gifsicle-bin/commit/ef40da8173aaef51b7c459b5c7f3a21a3b546e85

I don't want to upgrade my whole project so I can use this one module.

**Comment by 1000ch** [comment]
I believe this issue is solved by [`v6.0.3`](https://github.com/imagemin/gifsicle-bin/releases/tag/v6.0.3)

**Comment by acardinale** [comment]
Hi @1000ch , the issue has re-emerged with version 6.1.0
