### ISSUE TITLE
Error when trying to install modules with gifsicle dependency

### ISSUE THREAD

**Issue by doberkofler** [imagemin/gifsicle-bin#133]
I'm not sure if this package is the source of my problem when installing my node modules but starting about 12h ago I can no longer install my dependencies and get the following error message when using 'npm ci':

```cmd
npm ERR! code 1
npm ERR! path D:\buildbot_worker\app-fe\build\node_modules\gifsicle
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! compiling from source
npm ERR! Response code 404 (Not Found)
npm ERR! gifsicle pre-build test failed
npm ERR! Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
npm ERR! 'autoreconf' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
```

**Comment by BigMichi1** [comment]
having the same problem on my ci machine running ubuntu and latest version of node lts /npm

```
$ npm ci --cache .npm --prefer-offline
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code 1
npm ERR! path /builds/php/zend/node_modules/gifsicle
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! compiling from source
npm ERR! Response code 404 (Not Found)
npm ERR! gifsicle pre-build test failed
npm ERR! Error: Command failed: /bin/sh -c autoreconf -ivf
npm ERR! /bin/sh: 1: autoreconf: not found
npm ERR! 
npm ERR! 
npm ERR!     at /builds/php/zend/node_modules/bin-build/node_modules/execa/index.js:231:11
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async Promise.all (index 0)
npm ERR! A complete log of this run can be found in:
npm ERR!     /builds/php/zend/.npm/_logs/2021-11-24T09_40_12_133Z-debug.log
```

**Comment by RichDiaz** [comment]
The problem is NPM has a version of 5.3.0, https://www.npmjs.com/package/gifsicle see the versions tab.
So any packagae.json with "gifsicle": "^5.0.0",  gets the version 5.3.0 of gifsicle but there is no version 5.3.0 in this repository.

If you look at lib/index.js there is a URL which will look like this 
https://raw.githubusercontent.com/imagemin/gifsicle-bin/v5.3.0/vendor/
for version 5.3.0 and that is failing.  Any other version that exists in this repo the URL does not fail

Can we get version 5.3.0 back or can we get rid of 5.3.0 in NPM ?

**Comment by MondoGao** [comment]
yep, this repo's 5.3.0 tag is missing, that makes the downloading process of bin-wrapper failed.

**Comment by doberkofler** [comment]
@MondoGao Thank you for the fix. Unfortunately when trying to install imagemin-gifsicle, I still hit the same error message. Did I miss something?

**Comment by MondoGao** [comment]
> 

this fix was introduced in https://npmmirror.com/ with package manager cnpm, we rewrite gifsicle's version in that registry.

**Comment by MondoGao** [comment]
> @MondoGao Thank you for the fix. Unfortunately when trying to install imagemin-gifsicle, I still hit the same error message. Did I miss something?

this fix was introduced in https://npmmirror.com/ and cnpm, we simply rewrites v5.3.0 to v5.2.1 in our registry.
I did't fix this issue in this repo.

**Comment by MondoGao** [comment]
> @MondoGao Thank you for the fix. Unfortunately when trying to install imagemin-gifsicle, I still hit the same error message. Did I miss something?

Btw, I tried to fork this repo and fix that issue, but I can't find the corresponding commit with 5.3.0, I can't just tag a version with 5.3.0 without more information.

**Comment by doberkofler** [comment]
@MondoGao Sorry, but now I'm confused. The issue was fixed in a mirror repository of npm? Will it be fixed in the "official" npm repository?

**Comment by niksy** [comment]
@sindresorhus could you please explain this? I see you’ve pushed latest version so I guess you also pushed `5.3.0`?

**Comment by sindresorhus** [comment]
Yeah, sorry. I forgot to push the release.

https://github.com/imagemin/gifsicle-bin/releases/tag/v5.3.0
