### ISSUE TITLE
5.3.0 is error  

### ISSUE THREAD

**Issue by hangingpot** [imagemin/gifsicle-bin#134]
INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                          19:04:19

 error  in ./src/assets/images/icon01.gif

Syntax Error: Error: spawn G:\pop-lude-allmenu\shop-management\node_modules\_gifsicle@5.3.0@gifsicle\vendor\gifsicle.exe ENOENT

**Comment by MondoGao** [comment]
yep, this repo's 5.3.0 tag is missing, that makes the downloading process of bin-wrapper failed.

**Comment by jlenos-inflight** [comment]
Hitting this too, can confirm: 5.3.0 is error

**Comment by mmdiyul** [comment]
> Hitting this too, can confirm: 5.3.0 is error
> 
> Hit through trying to install https://github.com/imagemin/imagemin-gifsicle

I fix this issue by installing version 5.2.1

**Comment by sindresorhus** [comment]
Duplicate of #133
