### ISSUE TITLE
Completely freezes installation on symlinked node_modules directory

### ISSUE THREAD

**Issue by zanona** [imagemin/gifsicle-bin#47]
Steps to reproduce: 

- OSX 10.10.1
- node: v0.10.33
- npm: 2.1.11

```bash
cd ~/my-app
mkdir ~/node_modules
ln -s ~/node_modules ~/my-app
npm install gifsicle
```

Hangs installation forever with:
```
> gifsicle@2.0.1 postinstall /Users/zanona/my-app/node_modules/gifsicle
> node lib/install.js
```

**Comment by kevva** [comment]
Open an issue over at https://github.com/kevva/bin-wrapper.

**Comment by karlvr** [comment]
I'm investigating this in reference to imagemin/imagemin#68. I have narrowed it down to the files array in the `BinWrapper.prototype.symlink` function being empty in the successful case and containing a file in the failure case. It continues...
