### ISSUE TITLE
Not usable in an offline environment

### ISSUE THREAD

**Issue by mkjaer** [imagemin/gifsicle-bin#49]
We have an offline environment with a local NPM, bower etc. repository mirror.
Some dependencies are causing issues, among those, gifsicle-bin.

I narrowed the problem down by looking into the source and I found it has different URLs hardcoded into it. [Like here on line 23](https://github.com/imagemin/gifsicle-bin/blob/master/test/test.js).

Any chance this can be handled a different way?

**Comment by kevva** [comment]
That's just the tests, it doesn't have an impact on your code. And no, need to have an internet connection to download the needed binaries. Once you've installed this it should work offline though.
