### ISSUE TITLE
npm install / save 404 error

### ISSUE THREAD

**Issue by markh2081** [imagemin/gifsicle-bin#54]
Hi,

I have the following issue when I try to use imagemon (or install gifsicle with "npm install --save gifsicle" )

    > gifsicle@3.0.1 postinstall /tmp/1/node_modules/gifsicle
    > node lib/install.js

      ⚠ Redirected 10 times. Aborting.
      ⚠ gifsicle pre-build test failed
      ℹ compiling from source
      ✖ HTTPError: Response code 404 (Not Found)
        at EventEmitter.<anonymous> (/tmp/1/node_modules/got/index.js:188:24)
        at emitOne (events.js:77:13)
        at EventEmitter.emit (events.js:169:7)
        at Immediate._onImmediate (/tmp/1/node_modules/got/index.js:59:8)
        at processImmediate [as _immediateCallback] (timers.js:383:17)

I think this error is because the package is trying to download the file:

     http://www.lcdf.org/gifsicle/gifsicle-1.87.tar.gz

that don't  exist in the server (the last version is 1.88)

I saw that in the last version of the code on github is downloading the file from github directly, but in the 3.0.1 relase version code is still downloading the version 1.8.7 from lcdf.org

**Comment by shinnn** [comment]
Fixed in https://github.com/imagemin/gifsicle-bin/commit/046ee0e25cc9002a24d9fb230172466aabb20721.
