### ISSUE TITLE
Bad tag name causes installation failure on Windows

### ISSUE THREAD

**Issue by jorrit** [imagemin/gifsicle-bin#55]
In version 3.0.2 the `index.js` script downloads the following URL:
`https://raw.githubusercontent.com/imagemin/gifsicle-bin/3.0.2/vendor/win/x64/gifsicle.exe`
However, the tag name is `v3.0.2`, not `3.0.2`, so the file is actually at:
`https://raw.githubusercontent.com/imagemin/gifsicle-bin/v3.0.2/vendor/win/x64/gifsicle.exe`
I recommend that a new version and branch 3.0.3 are published, if the tag 3.0.2 can't be recreated.

**Comment by jorrit** [comment]
Looking at https://github.com/imagemin/jpegoptim-bin/blob/master/lib/index.js and https://github.com/imagemin/pngcrush-bin/blob/master/lib/index.js and other -bin packages it appears that gifsicle-bin deviates from the standard and should have the `v` in the script.

**Comment by jorrit** [comment]
I have checked more imagemin projects and some other projects also don't have the `v`. Perhaps update those so this understandable mistake does not happen in the future with those projects.

**Comment by shinnn** [comment]
Yes, we should add `v` to those, to avoid mistakes like this.

@jorrit PRs welcome if you have a time :)
