### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by mnpenner** [imagemin/gifsicle-bin#58]
gifsicle is failing to install on my FreeBSD machine.

```
$ npm i gifsicle
-
> gifsicle@3.0.3 postinstall /usr/local/myproject/node_modules/gifsicle
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/usr/local/myproject/node_modules/gifsicle/vendor" --bindir="/usr/local/myproject/node_modules/gifsicle/vendor" && make install
Command failed: /bin/sh -c autoreconf -ivf
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/share/autoconf-2.69/Autom4te/FileUtils.pm line 326.
autoreconf-2.69: failed to run aclocal: No such file or directory

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gifsicle@3.0.3 node_modules/gifsicle
├── logalot@2.1.0 (figures@1.4.0, squeak@1.3.0)
├── bin-wrapper@3.0.2 (os-filter-obj@1.0.3, lazy-req@1.1.0, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.4.3)
└── bin-build@2.2.0 (rimraf@2.5.0, archive-type@3.1.0, exec-series@1.0.2, url-regex@3.1.0, tempfile@1.1.1, decompress@3.0.0, download@4.4.3)
```

Would it be possible to add support, or is there something I need to pre-install?

**Comment by shinnn** [comment]
Currently this repository doesn't include x64 build for FreeBSD. https://github.com/imagemin/gifsicle-bin/tree/master/vendor/freebsd

@mnpenner Can you build [gifsicle](https://github.com/kohler/gifsicle) on 64bit FreeBSD and submit a pull request to this repository?

**Comment by mnpenner** [comment]
Sorry, took me some time to get back to this; I was on vacation. You just need the `gfisicle` bin right? GitHub won't let me attach it directly, so I've zipped it: [gifsicle.zip](https://github.com/imagemin/gifsicle-bin/files/90726/gifsicle.zip)

**Comment by mnpenner** [comment]
Okay, I built it and threw it in freebsd/x64. I'm a git/GitHub noob so hopefully I submitted the PR correctly :)

**Comment by mnpenner** [comment]
Thanks for merging this. Could you tag it? https://raw.githubusercontent.com/imagemin/gifsicle-bin/v3.0.3/vendor/freebsd/x64/gifsicle is returning a 404.

**Comment by mnpenner** [comment]
Bump. I'm still seeing 

```
> gifsicle@3.0.3 postinstall /usr/local/webenginex/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Response code 404 (Not Found)
```

Could you either tag this, or change the URL used to `https://raw.githubusercontent.com/imagemin/gifsicle-bin/master/vendor/freebsd/x64/gifsicle` so that we always get the latest bin?
