### ISSUE TITLE
giflossy

### ISSUE THREAD

**Issue by denji** [imagemin/gifsicle-bin#62]
Based on **gifsicle** which implements lossy LZW compression. It can reduce animgif file sizes by 30%—50% at a cost of some dithering/noise.

* https://pornel.net/lossygif @pornel
* https://github.com/pornel/giflossy

**Comment by sindresorhus** [comment]
I don't have time to make a wrapper module for this, but maybe @shinnn or @kevva does.

**Comment by shinnn** [comment]
I'm waiting for https://github.com/kohler/gifsicle/pull/16 to be merged.

**Comment by pornel** [comment]
The PR has been open for so long now, that I lost hope it'll ever be merged.

**Comment by shinnn** [comment]
OK I'll create imagemin/giflossy-bin.

**Comment by shinnn** [comment]
@denji First, can you help fixing merge conflict of the @pornel's pull request?

https://github.com/kohler/gifsicle/pull/16#issuecomment-181295112

> If someone wants to help, there's a merge conflict that needs to be resolved.

Then if the PR is still ignored by the Gifsicle author for a long time, I'll create a giflossy wrapper. Maintaining two wrappers for almost the same functionality is not the best solution.

**Comment by denji** [comment]
> If someone wants to help, there's a merge conflict that needs to be resolved.

I'm not sure that after resolving a merge conflict will it immediately in the upstream, is this possible?

**Comment by shinnn** [comment]
> I'm not sure that after resolving merge conflict will it immediately in the upstream

No, after resolving merge conflict, the Gifsicle repository owner should merge and commit it to the master branch.

============

I'm not able to fully understand what @denji tried to say in https://github.com/imagemin/gifsicle-bin/issues/62#issuecomment-233191283.

**Comment by denji** [comment]
https://github.com/kohler/gifsicle/pull/72
