### ISSUE TITLE
Ubuntu ASP NET Core installing ASPNetMVC

### ISSUE THREAD

**Issue by sancas** [imagemin/gifsicle-bin#64]
I was trying to install a template for ASP Net MVC in Ubuntu 16.04 but I can't because it says maybe it is a problem with this library, here is my log.

[npm-debug.txt](https://github.com/imagemin/gifsicle-bin/files/462923/npm-debug.txt)

Hope it helps a lot, if someone found something for help me I'll periodically check this

**Comment by kevva** [comment]
You're trying to install version `0.1.7`. It's kinda ancient, try installing the newest instead.
