### ISSUE TITLE
Path is a URL

### ISSUE THREAD

**Issue by patrikx3** [imagemin/gifsicle-bin#65]
Can you know how to use it?
![image](https://cloud.githubusercontent.com/assets/4770180/19019880/d12f4fe4-8896-11e6-8d78-801583ff3283.png)

it looks like is using a url instead of a path.

**Comment by filingroove** [comment]
+1 on this. 

`optipng-bin` has this issue too

**Comment by tomhatzer** [comment]
+1

optipng-bin and jpegtran-bin and gifsicle-bin all share the same error.

**Comment by kevva** [comment]
Use a newer version. `0.1.7` is very, very old.
