### ISSUE TITLE
Installation is really slow

### ISSUE THREAD

**Issue by jsCONFIG** [imagemin/gifsicle-bin#67]
Every time I install, it must take a long time in the "node lib/install.js" process.I really can not stand.

**Comment by haobingwang** [comment]
So am I. It taked me a hour more and  do nothing.Just because we in China 💩 .  Should F**k the GFW? I use the mirror of npm registry.
mac os 10.12.1
npm 3.10.5
node 4.4.7,6.6.1

Is pot of cook 😭

**Comment by rccoder** [comment]
F**，half hours ago

**Comment by shinnn** [comment]
Closing for some impolite comments. Just use normal, GFW-free network.
