### ISSUE TITLE
Failed at the gifsicle@0.1.7 postinstall script 'node index.js'- While installing NODE-EXRESS

### ISSUE THREAD

**Issue by arssonist** [imagemin/gifsicle-bin#69]
I was trying to install NPM NODE EXPRESS and got an error from your package.

`ailed at the gifsicle@0.1.7 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gifsicle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chrisdielschnieder/Desktop/code_work/api/api_shopify_express/npm-debug.log
`
I don't really need your package it just seems to be in there. Can I leave it out? NPM and NODE are up to date.

**Comment by nessup** [comment]
@arssonist Did you ever figure this out? I'm in exactly the same situation :(

**Comment by arssonist** [comment]
@nessup I did, but sorry man I don't remember how. I do know that the error message was bogus and following the advice, that there was an error in the package, was why I posted here. I prob had an error somewhere else, like a typo. But yeah, can't remember.

**Comment by arssonist** [comment]
Problem not solved, but can't seem to describe it any longer. Possible NPM problem. Anyway, closing.

**Comment by nternetinspired** [comment]
Installing the package on it's own resolved this error for me. https://github.com/imagemin/gifsicle-bin/issues/72#issuecomment-287749058
