### ISSUE TITLE
Failed at gifsicle@3.0.4 postinstall script 'node lib/install.js'

### ISSUE THREAD

**Issue by MichaelDWheeler** [imagemin/gifsicle-bin#70]
Hello. I am getting the following error and I can't proceed on my project as it crashes. Does anyone know how to fix it?

![error](https://cloud.githubusercontent.com/assets/6476041/22815753/8570348c-ef12-11e6-9cca-747d070a5764.jpg)

**Comment by MichaelDWheeler** [comment]
I restarted my computer and it fixed it. On Windows...

**Comment by raelmiu** [comment]
I get this same error, consistently, on Mac OS (sierra). Even after reboot. :)
`npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@3.0.4 postinstall script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gifsicle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jesperbylund/Documents/Projects.Local/BlankPage/npm-debug.log`

**Comment by yar-trach** [comment]
Same on Ubuntu 16.04, rebooting doesn't help.

**Comment by yar-trach** [comment]
I've fixed this problem, here you can find my answer:
https://stackoverflow.com/questions/42152533/npm-fails-when-installing-image-webpack-loader-i-cant-proceed-with-my-project

**Comment by jcklpe** [comment]
Thanks @yar-trach 

I might be understanding things incorrectly but this issue seems to happen due to imagemin trying to install gifsicle globally? Shouldn't that be changed? it seems that while your issue can fix the problem, that the way imagemin is pulling it's dep is not as contained and portable as it could be. I encountered this problem when trying to run imagemin on a VPS without root access which seems to me that it would be a pretty common use case for people.

**Comment by anysunflower** [comment]
resart work for me in unbuntu 18

**Comment by kluplau** [comment]
> I might be understanding things incorrectly but this issue seems to happen due to imagemin trying to install gifsicle globally?

On my end it's because it's fetching something from Github with an HTTP request, which my corporate firewall doesn't allow.

**Comment by aamiriqubal** [comment]
`brew install automake`

For mac os users (Catalina), this should work.
