### ISSUE TITLE
how to use option

### ISSUE THREAD

**Issue by okfirelee** [imagemin/gifsicle-bin#71]
execFile(gifsicle, ['-o', 'output.gif', 'jiaowagif.gif'], err => {
    console.log('Image minified!');
});
it works and console image minified
how to use other options 
source : gifsicle -O3 --colors 30 big.gif -o big2.gif

**Comment by gsaha36** [comment]
Hey did you find a way to include options?

**Comment by 1000ch** [comment]
Pass options to second argument for [`execFile`](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) as Array.

```javascript
const {execFile} = require('child_process');

execFile(gifsicle, ['--interlace', '--optimize', '5', '-o', 'output.gif', 'input.gif'], err => {
  if (err) {
    console.error(err);
  }
});
```
