### ISSUE TITLE
gifsicle@0.1.7 postinstall node index.js

### ISSUE THREAD

**Issue by 860git** [imagemin/gifsicle-bin#72]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@0.1.7 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gifsicle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\markdown-preview-enhanced\markdown-preview-enhanced\npm-debug.lo
g

**Comment by 860git** [comment]
after git clone markdown-preview-enhanced successfully
error occure when do 'npm install'

**Comment by keithmancuso** [comment]
Im getting the same error, and i dont even need this package.

npm ERR! gifsicle@0.1.7 postinstall: `node index.js`

Im using node 7.7.1

whats going on?

**Comment by 860git** [comment]
on Windows 7 64bit.
'node' is the newest version(v6.10.0) 'npm'(v3.10.10)

**Comment by forevergirl4** [comment]
I'm also getting this error in heroku.
npm ERR! gifsicle@0.1.7 postinstall: node index.js

I'm using node 6.9.5

**Comment by nternetinspired** [comment]
Installing the package on it's own resolved this error for me;

`npm install imagemin-gifsicle`

I was then able to successfully  `npm install` the rest of my project dependencies.

**Comment by piux** [comment]
same error tried installing gifsicle like the @nternetinspired  said and still tries to install gifsicle 0.1.7.

im using windows 8.1 and node.js 7.1.0, even tried reinstalling node and no success.

**Comment by raelmiu** [comment]
I'm having the same issue on Mac OS (sierra). Even installing it separately as @nternetinspired proposed gives the same error.

**Comment by kostiak-guardicore** [comment]
Installing it under the latest node 4.x worked.

**Comment by kevva** [comment]
`gifsicle@0.1.7` is really old. You should update or open an issue on the repository for the module you're using that makes use of it.
