### ISSUE TITLE
How to define maxBuffer in execFile?

### ISSUE THREAD

**Issue by gsaha36** [imagemin/gifsicle-bin#75]
I am trying this code for optimizing images but maxbuffer gets exceeded still. Where it should be defined?

```
execFile(gifsicle,['-O1', './public/output.gif', inputFilename],{maxBuffer: 1024 * 500}, err => {
                  if(err)
                    reject(err);
                  else
                  {  
                    resolve("success");
                    console.log('Image minified!');
                  }
                  });
```

**Comment by kevva** [comment]
That looks correct to me. See the docs for further info https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback.
