### ISSUE TITLE
gifsicle@3.0.4 postinstall: `node lib/install.js`

### ISSUE THREAD

**Issue by rongxingsun** [imagemin/gifsicle-bin#76]
windows 7 /node v6.11.0  
 Failed at the gifsicle@3.0.4 postinstall script 'node lib/install.js'.

**Comment by matthewchrist** [comment]
I am also facing this issue with the following versions of node and npm:

20:09:13 [0m[91mnpm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
20:09:13 npm ERR! node v6.10.0
20:09:13 npm ERR! npm  v3.10.10
20:09:13 npm ERR! code ELIFECYCLE
20:09:13 
20:09:13 [0m[91mnpm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
20:09:13 npm ERR! Exit status 1
20:09:13 npm ERR! 
20:09:13 npm ERR! Failed at the gifsicle@3.0.4 postinstall script 'node lib/install.js'.
20:09:13 npm ERR! Make sure you have the latest version of node.js and npm installed.
20:09:13 npm ERR! If you do, this is most likely a problem with the gifsicle package,
20:09:13 npm ERR! not with npm itself.
20:09:13 npm ERR! Tell the author that this fails on your system:
20:09:13 npm ERR!     node lib/install.js
20:09:13 npm ERR! You can get information on how to open an issue for this project with:
20:09:13 npm[0m[91m ERR!     npm bugs gifsicle
20:09:13 npm ERR![0m[91m Or if that isn't available, you can get their info via:
20:09:13 npm ERR!     npm owner ls gifsicle
20:09:13 npm ERR! There is likely additional logging output above.
20:09:13 [0m[91m
20:09:13 [0m[91mnpm ERR! Please include the following file with any support request:
20:09:13 npm ERR!     /apps/npm-debug.log

**Comment by adridev** [comment]
Getting the same error. The install.js script fails due to a "permission denied" error when it tries to run vendor/gifsicle --version

env:
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        17.0.5
NodeJS: v8.5.0
NPM: 5.4.2

**Comment by eromoe** [comment]
I just see npm stuck at 
```
> gifsicle@3.0.4 postinstall /mnt/annotator/node_modules/gifsicle
> node lib/install.js
```

for over half hour.

**Comment by Brotzka** [comment]
Me too..

Any solutions?

**Comment by IamAnotherOne** [comment]
Same error here,
node v8.9.4
npm 5.6.0
win7 64bit

Any solutions?

**Comment by bcdbuddy** [comment]
with this gifsicle thing I downgraded npm to 5.1.0 `npm i npm@5.1.0 -g`

**Comment by niallobrien** [comment]
Same issue here, Windows 7 64bit.

**Comment by kurenov** [comment]
Got the same issue. NPM stuck at gifsicle post installation. Ubuntu 16.04 node 9.6.1, npm 5.6.1 & Kubuntu 16.04, node 9.5.0, npm 5.6.0
Tried to downgrade 5.1.0, but it did not help.

**Comment by itexpertsindya** [comment]
Having the Same issue here, on my MacBook gifsicle refuses to install and throws error at post installation.

**Comment by pezetko** [comment]
Isn't there a problem that if you're behind a corporate proxy (meaning that you do not have access to GitHub) that lib/install.js simply fails because it is trying to fetch "https://github.com/kohler/gifsicle/archive/v1.90.tar.gz" ?
I do not think it is correct to hardcode the URL there without any possibility to configure it against any HTTP(S) proxy.

**Comment by jasonday** [comment]
Still running into this issue. Running behind a corporate proxy and with Artifactory as well. Looking across the nets, it appears gifsicle fails builds for a lot of users. A solution would be appreciated.

**Comment by syedsimanta03** [comment]
same issue windows 10 node 12.13.1

**Comment by lamvananh** [comment]
me too this make my npm install not worrking anymore

**Comment by steven7mwesigwa** [comment]
> I just see npm stuck at
> 
> ```
> > gifsicle@3.0.4 postinstall /mnt/annotator/node_modules/gifsicle
> > node lib/install.js
> ```
> 
> for over half hour.

I had to cancel the operation with CTRL + C in Windows 10 Power Shell
Then I ran `npm install gifsicle@3.0.4`
After successful installation of the package, I then ran `npm install` again. And that completed quickly and successfully.

**Comment by 1000ch** [comment]
Please try the newest version.

**Comment by Leslie-Wong-H** [comment]
This works for me. Win 10. 
> npm install -g cnpm --registry=https://registry.npm.taobao.org
> cnpm install gifsicle -D

**Comment by lenchevskii** [comment]
The same error occurred (Ubuntu 20.04.1, Node v14.15.1)

![Screenshot from 2020-12-16 11-30-08](https://user-images.githubusercontent.com/46607022/102325057-bc7d4200-3f93-11eb-8f16-f9300849ae78.png)

Then I tried:


> This works for me. Win 10.
> 
> > npm install -g cnpm --registry=https://registry.npm.taobao.org
> > cnpm install gifsicle -D

But nothing changed:

![Screenshot from 2020-12-16 11-40-11](https://user-images.githubusercontent.com/46607022/102325339-14b44400-3f94-11eb-8ef3-d5d10adaa3b4.png)

**Comment by r692802421** [comment]
This works for me. Win 7.

npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install gifsicle -D

it waste my half of day time！！！
from 9:00 to 15:30!

**Comment by weishao888** [comment]
today,i am here again!
解决方法如下：
方案1：
去掉webpack压缩功能即可运行ok，需要删除2个插件，image-webpack-loader和webpack-parallel-uglify-plugin，将webpack的config文件夹里面的index.js里面的配置productionGzip的值改为false，webpack.prod.conf.js里面的new UglifyJsPlugin全部是注释掉，webpack.base.conf.js里面的image-webpack-loader部分也注释掉，package.json上述插件都要删掉。
webpack-image-loader（image-webpack-loader）依赖的四个图片处理库都需要拉取bin文件
"dependencies": {
"imagemin-gifsicle": "^5.1.0",
"imagemin-mozjpeg": "^6.0.0",
"imagemin-pngquant": "^5.0.0",
"imagemin-svgo": "^5.2.1",
}，package.json里面的这4个图片处理库全部删掉，然后npm i即可下载成功，运行、打包都ok，20230707特此记录，详情配置见公用督办系统。
方案2：
直接cnpm i 安装就不会有这个问题！（因为上述插件image-webpack-loader依赖的4个图片处理库在github上无法正常全部下载，所以用npm i下载不全，导致出错！）
