### ISSUE TITLE
Remove gulp-util

### ISSUE THREAD

**Issue by amaujipe** [imagemin/gifsicle-bin#85]
I'm using your plugin in a personal project. But it have some warnings with gulp-util. Can you follow this recomendations to remove that?

gutil.File => https://www.npmjs.com/package/vinyl
gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext
gutil.colors => https://www.npmjs.com/package/ansi-colors
gutil.date => https://www.npmjs.com/package/date-format
gutil.log => https://www.npmjs.com/package/fancy-log
gutil.template => https://www.npmjs.com/package/lodash.template
gutil.env => https://www.npmjs.com/package/minimist
gutil.beep => https://www.npmjs.com/package/beeper
gutil.noop => https://www.npmjs.com/package/through2
gutil.isStream => Use the .isStream() method on Vinyl objects
gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
gutil.isNull => Use the .isNull() method on Vinyl objects
gutil.linefeed => Use the string '\n' in your code
gutil.combine => https://www.npmjs.com/package/multipipe
gutil.buffer => https://www.npmjs.com/package/list-stream
gutil.PluginError => https://www.npmjs.com/package/plugin-error

**Comment by rinella** [comment]
i think the problem is with bin-wrapper using an older version of download

**Comment by joshlewis** [comment]
You need to update your dependency on bin-build to at least version 3.0.0. See here: https://github.com/kevva/bin-build/issues/11

**Comment by rinella** [comment]
bin-build 3.0 does not have gulp-util, but gifsicle now uses bin-wrapper.  bin wrapper has gulp-util.

**Comment by karstens** [comment]
Looks like this wasn't released (https://github.com/imagemin/gifsicle-bin/commit/7f88f03e5def54531cf6f25db53e4e2da2cd8c4b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). Or what might block this?

**Comment by dereckson** [comment]
The current dependency tree is this one:

```
│   └─┬ gifsicle@3.0.4
│     └─┬ bin-build@2.2.0
│       └─┬ download@4.4.3
│         └─┬ gulp-decompress@1.2.0
│           └── gulp-util@3.0.8  deduped
```

**ALL** those dependencies have been updated.

So, to upgrade bin-wrapper is a good first move.
