### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by rejas** [imagemin/gifsicle-bin#90]
Hi, what is the plan for releaseing a new version since the package updates regarding bin-build etc are in the code but not yet out in an official release? Would help a lot with some warnings people and myself are getting. Cheers, V

**Comment by markwoon** [comment]
@kevva @shinnn Any idea when the a new version can be released?

**Comment by virginielgb** [comment]
Hi,
Would including the package directly from github do the trick for you? 
Like, using
npm install https://github.com/imagemin/gifsicle-bin

**Comment by markwoon** [comment]
Not really.  I would want to use an official release.

**Comment by DesWurstes** [comment]
@kevva @shinnn Just release it, please. Let's throw away gulp-util.

**Comment by cat5inthecradle** [comment]
Also #92

**Comment by 1000ch** [comment]
[bin-wrapper v4](https://github.com/kevva/bin-wrapper/releases/tag/v4.0.0) including the newest [download](https://github.com/kevva/download) is released. So updated dependencies and requires Node.js v6~ (041aaf6).

**Comment by LuisUrrutia** [comment]
What happen with it ?

**Comment by 1000ch** [comment]
As far as I debugged on my local, `gifsicle` (Executable file) authority seems to be changed when download with [`download`](https://github.com/kevva/download). But I'm not sure about what causes this. Ping @sindresorhus

**Comment by realityking** [comment]
You're probably running into kevva/bin-wrapper#67

**Comment by 1000ch** [comment]
Released [v4.0.0](https://github.com/imagemin/gifsicle-bin/releases/tag/v4.0.0).
