### ISSUE TITLE
remove gulp-util using the following API replacements:

### ISSUE THREAD

**Issue by nomadtechiemike** [imagemin/gifsicle-bin#91]
gutil.File => https://www.npmjs.com/package/vinyl
    gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext
    gutil.colors => https://www.npmjs.com/package/ansi-colors
    gutil.date => https://www.npmjs.com/package/date-format
    gutil.log => https://www.npmjs.com/package/fancy-log
    gutil.template => https://www.npmjs.com/package/lodash.template
    gutil.env => https://www.npmjs.com/package/minimist
    gutil.beep => https://www.npmjs.com/package/beeper
    gutil.noop => https://www.npmjs.com/package/through2
    gutil.isStream => Use the .isStream() method on Vinyl objects
    gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
    gutil.isNull => Use the .isNull() method on Vinyl objects
    gutil.linefeed => Use the string '\n' in your code
    gutil.combine => https://www.npmjs.com/package/multipipe
    gutil.buffer => https://www.npmjs.com/package/list-stream
    gutil.PluginError => https://www.npmjs.com/package/plugin-error

**Comment by rejas** [comment]
Those changes are already in the code, but the maintainers havent released a new version yet. Feel free to comment in this issue https://github.com/imagemin/gifsicle-bin/issues/90

**Comment by cat5inthecradle** [comment]
The larger problems that this issue was inspired by will still be a problem until #92 is resolved and the new version is deployed to npm.
