### ISSUE TITLE
Publish the newest version to npm

### ISSUE THREAD

**Issue by georgiik-welldone** [imagemin/gifsicle-bin#92]
There are unpublished important changes https://github.com/imagemin/gifsicle-bin/commit/7f88f03e5def54531cf6f25db53e4e2da2cd8c4b

```
"bin-build": "^3.0.0",
```

without those changes we are not able to install this plugin on node >= v8 if npmrc contains `engine-strict = true`

**Comment by 1000ch** [comment]
I'll publish a new _patch_ version. 

@kevva 
Please tell me if there are any problems (I'm not sure about why not released).

**Comment by 1000ch** [comment]
I'll merge #89 before publishing.

**Comment by 1000ch** [comment]
As I mentioned in https://github.com/imagemin/gifsicle-bin/issues/90#issuecomment-402608033, we should also update bin-wrapper.

**Comment by creage** [comment]
could we have this task complete please?

**Comment by 1000ch** [comment]
Released [v4.0.0](https://github.com/imagemin/gifsicle-bin/releases/tag/v4.0.0).
